version: '3'
services:
    nginx:
        volumes:
            - /var/www/vse-avtoservisy.ru/app/web:/var/www/vse-avtoservisy.ru/app/web
            - /var/www/avto-servisy/app/web:/var/www/avto-servisy/app/web
            - /var/www/cabinet/app/web/:/var/www/cabinet/app/web/
            - /var/www/salonrk/web:/var/www/salonrk/web
            - /var/www/laravel/public:/var/www/laravel/public
            - /var/www/developer-pro.ru/public:/var/www/developer-pro.ru/public
            - /var/www/hostels-msk.ru/web:/var/www/hostels-msk.ru/web
            - /var/www/api.hostels-msk.ru/public:/var/www/api.hostels-msk.ru/public
            - /var/www/service_network_2/app/web/servisy-nissan.ru:/var/www/service_network_2/app/web/servisy-nissan.ru
            - /var/www/service_network/app/web/:/var/www/service_network/app/web/
            - /var/www/service_network_3/app/web/:/var/www/service_network_3/app/web/
            - /var/www/service_network_4/app:/var/www/service_network_4/app
    php-cli-7.1:
        volumes:
            - /var/www/salonrk:/var/www/salonrk
            - /var/www/vse-avtoservisy.ru:/var/www/vse-avtoservisy.ru
            - /var/www/avto-servisy:/var/www/avto-servisy
            - /var/www/cabinet:/var/www/cabinet
            - /var/www/service_network_2/app:/var/www/service_network_2/app
            - /var/www/service_network/app:/var/www/service_network/app
            - /var/www/service_network_3/app:/var/www/service_network_3/app
            - /var/www/service_network_4/app:/var/www/service_network_4/app
        links:
            - rabbitmq
    php-fpm-7.1:
        volumes:
            - /var/www/salonrk:/var/www/salonrk
            - /var/www/vse-avtoservisy.ru:/var/www/vse-avtoservisy.ru
            - /var/www/avto-servisy:/var/www/avto-servisy
            - /var/www/cabinet:/var/www/cabinet
            - /var/www/service_network_2/app:/var/www/service_network_2/app
            - /var/www/service_network/app:/var/www/service_network/app
            - /var/www/service_network_3/app:/var/www/service_network_3/app
            - /var/www/service_network_4/app:/var/www/service_network_4/app
        links:
            - redis
            - rabbitmq
        extra_hosts:
            - "avto-servisy.loc:${CLIENT_HOST}"
    php-cli-7.3:
        volumes:
            - /var/www/laravel:/var/www/laravel
            - /var/www/developer-pro.ru:/var/www/developer-pro.ru
            - /var/www/hostels-msk.ru:/var/www/hostels-msk.ru
            - /var/www/api.hostels-msk.ru:/var/www/api.hostels-msk.ru
            - /var/www/service_network/app/:/var/www/service_network/app/
    php-fpm-7.3:
        volumes:
            - /var/www/laravel:/var/www/laravel
            - /var/www/developer-pro.ru:/var/www/developer-pro.ru
            - /var/www/hostels-msk.ru:/var/www/hostels-msk.ru
            - /var/www/api.hostels-msk.ru:/var/www/api.hostels-msk.ru
            - /var/www/service_network/app/:/var/www/service_network/app/