version: '3'
services:
    nginx:
        volumes:
            - /var/www:/var/www
    php-cli-7.1:
        volumes:
            - /var/www:/var/www
        links:
            - rabbitmq
    php-fpm-7.1:
        volumes:
            - /var/www:/var/www
        links:
            - redis
            - rabbitmq
        extra_hosts:
            - "avto-servisy.loc:${CLIENT_HOST}"
    php-cli-7.3:
        volumes:
            - /var/www:/var/www
    php-fpm-7.3:
        volumes:
            - /var/www:/var/www