version: '3'
services:
    nginx:
        volumes:
            - /var/www/vse-avtoservisy.ru/app/web:/var/www/vse-avtoservisy.ru/app/web
            - /var/www/avto-servisy/app/web:/var/www/avto-servisy/app/web
            - /var/www/cabinet/app/web/:/var/www/cabinet/app/web/
            - /var/www/salonrk/web:/var/www/salonrk/web
        links:
            - php-fpm-7.1
            - php-fpm-7.3
            - node
    php-cli-7.1:
        volumes:
            - /var/www/salonrk:/var/www/salonrk
            - /var/www/vse-avtoservisy.ru:/var/www/vse-avtoservisy.ru
            - /var/www/avto-servisy:/var/www/avto-servisy
            - /var/www/cabinet:/var/www/cabinet
        links:
            - rabbitmq
    php-fpm-7.1:
        volumes:
            - /var/www/salonrk:/var/www/salonrk
            - /var/www/vse-avtoservisy.ru:/var/www/vse-avtoservisy.ru
            - /var/www/avto-servisy:/var/www/avto-servisy
            - /var/www/cabinet:/var/www/cabinet
        links:
            - redis
            - rabbitmq
        extra_hosts:
            - "avto-servisy.loc:${CLIENT_HOST}"
    node:
        volumes:
            - /var/www/cabinet:/var/www/cabinet
        user: "1000"
        links:
            - redis
        command: node /var/www/cabinet/app/nodejs/server.js