version: '3'
services:
    nginx:
        volumes:
            - /var/www:/var/www
    php-cli-7.1:
        volumes:
            - /var/www:/var/www
    php-fpm-7.1:
        volumes:
            - /var/www:/var/www
    php-cli-7.3:
        volumes:
            - /var/www:/var/www
    php-fpm-7.4:
        volumes:
            - /var/www:/var/www
