version: '3'
services:
    nginx:
        volumes:
            - /var/www/api.hostels-msk.ru/public:/var/www/api.hostels-msk.ru/public
            - /var/www/hostels-msk.ru/web:/var/www/hostels-msk.ru/web
            - /var/www/developer-pro.ru/public:/var/www/developer-pro.ru/public
            - /var/www/vse-avtoservisy.ru/app/web:/var/www/vse-avtoservisy.ru/app/web
            - /var/www/cabinet/app/web/:/var/www/cabinet/app/web/
    php-cli-7.1:
        volumes:
            - /var/www/vse-avtoservisy.ru:/var/www/vse-avtoservisy.ru
            - /var/www/cabinet:/var/www/cabinet
    php-fpm-7.1:
        volumes:
            - /var/www/vse-avtoservisy.ru:/var/www/vse-avtoservisy.ru
            - /var/www/cabinet:/var/www/cabinet
    php-cli-7.3:
        volumes:
            - /var/www/api.hostels-msk.ru:/var/www/api.hostels-msk.ru
            - /var/www/hostels-msk.ru:/var/www/hostels-msk.ru
            - /var/www/developer-pro.ru:/var/www/developer-pro.ru
    php-fpm-7.3:
        volumes:
            - /var/www/api.hostels-msk.ru:/var/www/api.hostels-msk.ru
            - /var/www/hostels-msk.ru:/var/www/hostels-msk.ru
            - /var/www/developer-pro.ru:/var/www/developer-pro.ru
