up:
	cp docker-compose.override.work.yml docker-compose.override.yml
	sudo service environmentd start
down:
	sudo service environmentd stop
nginx-build:
	docker-compose build nginx
restart:
	down && up